# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='turn',
            new_name='round_count',
        ),
        migrations.AddField(
            model_name='game',
            name='round_over',
            field=models.BooleanField(default=False),
        ),
    ]
