# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170211_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round_over',
            field=models.BooleanField(default=True),
        ),
    ]
