"""empty message

Revision ID: 2f53c00531f4
Revises: 
Create Date: 2017-07-24 02:24:20.553979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f53c00531f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=True),
    sa.Column('board_to_play', sa.Integer(), nullable=True),
    sa.Column('intake_cols', sa.Integer(), nullable=True),
    sa.Column('available_pickle', sa.PickleType(), nullable=True),
    sa.Column('board_list_pickle', sa.PickleType(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('board_played', sa.String(length=25), nullable=True),
    sa.Column('moves', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permanent',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapid',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=25), nullable=False),
    sa.Column('beads_in', sa.Integer(), nullable=True),
    sa.Column('beads_out', sa.Integer(), nullable=True),
    sa.Column('end_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('unsheltered', sa.Integer(), nullable=True),
    sa.Column('market', sa.Integer(), nullable=True),
    sa.Column('rapid', sa.Integer(), nullable=True),
    sa.Column('perm', sa.Integer(), nullable=True),
    sa.Column('emerg_total', sa.Integer(), nullable=True),
    sa.Column('trans_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transitional',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('no_red', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unsheltered',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unsheltered')
    op.drop_table('transitional')
    op.drop_table('score')
    op.drop_table('record')
    op.drop_table('rapid')
    op.drop_table('permanent')
    op.drop_table('outreach')
    op.drop_table('market')
    op.drop_table('log')
    op.drop_table('emergency')
    op.drop_table('game')
    # ### end Alembic commands ###
