"""empty message

Revision ID: 360a398b3094
Revises: b157e2180aba
Create Date: 2017-07-01 19:17:19.568506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360a398b3094'
down_revision = 'b157e2180aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'intake')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('intake', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
