"""empty message

Revision ID: 3c6058e141f5
Revises: 
Create Date: 2017-08-27 23:58:00.015680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6058e141f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=True),
    sa.Column('board_to_play', sa.Integer(), nullable=True),
    sa.Column('intake_cols', sa.Integer(), nullable=True),
    sa.Column('available_pickle', sa.PickleType(), nullable=True),
    sa.Column('board_num_list_pickle', sa.PickleType(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('board_num', sa.Integer(), nullable=False),
    sa.Column('beads', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permanent',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapid',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('from_board_num', sa.Integer(), nullable=False),
    sa.Column('to_board_num', sa.Integer(), nullable=False),
    sa.Column('beads_moved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transitional',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('no_red', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unsheltered',
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unsheltered')
    op.drop_table('transitional')
    op.drop_table('record')
    op.drop_table('rapid')
    op.drop_table('permanent')
    op.drop_table('outreach')
    op.drop_table('market')
    op.drop_table('emergency')
    op.drop_table('decision')
    op.drop_table('count')
    op.drop_table('game')
    # ### end Alembic commands ###
