"""empty message

Revision ID: 5627481abc2c
Revises: a24ade893296
Create Date: 2017-06-17 15:59:52.206012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5627481abc2c'
down_revision = 'a24ade893296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanent', sa.Column('record', sa.PickleType(), nullable=True))
    op.add_column('rapid', sa.Column('record', sa.PickleType(), nullable=True))
    op.drop_column('score', 'transitional_count')
    op.drop_column('score', 'emergency_count')
    op.add_column('transitional', sa.Column('record', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transitional', 'record')
    op.add_column('score', sa.Column('emergency_count', sa.BLOB(), nullable=True))
    op.add_column('score', sa.Column('transitional_count', sa.BLOB(), nullable=True))
    op.drop_column('rapid', 'record')
    op.drop_column('permanent', 'record')
    # ### end Alembic commands ###
