"""empty message

Revision ID: a24ade893296
Revises: 247ef3fb4bb8
Create Date: 2017-06-16 09:30:21.045615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24ade893296'
down_revision = '247ef3fb4bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency', sa.Column('record', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency', 'record')
    # ### end Alembic commands ###
