"""empty message

Revision ID: 0c7c1459e19e
Revises: f9d383bb25e9
Create Date: 2017-03-28 09:57:58.915952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7c1459e19e'
down_revision = 'f9d383bb25e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency', sa.Column('room', sa.Integer(), nullable=True))
    op.add_column('permanent', sa.Column('room', sa.Integer(), nullable=True))
    op.add_column('rapid', sa.Column('room', sa.Integer(), nullable=True))
    op.add_column('transitional', sa.Column('room', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transitional', 'room')
    op.drop_column('rapid', 'room')
    op.drop_column('permanent', 'room')
    op.drop_column('emergency', 'room')
    # ### end Alembic commands ###
