"""empty message

Revision ID: 9ec6bcc0cd00
Revises: 66dba24c5dba
Create Date: 2017-06-08 00:30:34.725556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec6bcc0cd00'
down_revision = '66dba24c5dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('emergency_total', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('transitional_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'transitional_total')
    op.drop_column('score', 'emergency_total')
    # ### end Alembic commands ###
